### ISSUE TITLE
undefined local variable or method `match_level_keys'

### ISSUE THREAD

**Issue by mramasco** [applitools/eyes.sdk.ruby#182]
I am trying to get https://applitools.com/tutorials/selenium-ruby.html#install-the-sdk example working. I installed the gem as instructed, created a ruby file with the same code as the example and updated it to use my api key. When I run the example I get:

```
Traceback (most recent call last):
	9: from applitest.rb:13:in `<main>'
	8: from /Users/mark.ramasco/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/delegate.rb:83:in `method_missing'
	7: from /Users/mark.ramasco/.rvm/gems/ruby-2.5.3/gems/eyes_selenium-3.15.21/lib/applitools/selenium/selenium_eyes.rb:499:in `test'
	6: from applitest.rb:20:in `block in <main>'
	5: from /Users/mark.ramasco/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/delegate.rb:83:in `method_missing'
	4: from /Users/mark.ramasco/.rvm/gems/ruby-2.5.3/gems/eyes_selenium-3.15.21/lib/applitools/selenium/selenium_eyes.rb:240:in `check_window'
	3: from /Users/mark.ramasco/.rvm/gems/ruby-2.5.3/gems/eyes_selenium-3.15.21/lib/applitools/selenium/selenium_eyes.rb:288:in `check'
	2: from /Users/mark.ramasco/.rvm/gems/ruby-2.5.3/gems/eyes_selenium-3.15.21/lib/applitools/selenium/selenium_eyes.rb:360:in `check_in_frame'
	1: from /Users/mark.ramasco/.rvm/gems/ruby-2.5.3/gems/eyes_selenium-3.15.21/lib/applitools/selenium/selenium_eyes.rb:292:in `block in check'
/Users/mark.ramasco/.rvm/gems/ruby-2.5.3/gems/eyes_core-3.15.21/lib/applitools/core/eyes_base.rb:518:in `update_default_settings': undefined local variable or method `match_level_keys' for #<Applitools::Selenium::SeleniumEyes:0x00007f81b794f620> (NameError)
```

I know it is at least reaching out to my Applitools account because I see the tests being created but they are pretty much empty. I am using a trial account so maybe the SDK is getting back something from the API and not handling it properly?

**Comment by nikita-andreev** [comment]
Fixed in 3.15.22
